[package]
name = "json_mask"
description = "Filter a JSON object as a tree to a subset using a JSON Schema as a mask"
version = "0.1.0"
edition = "2021"
authors = ["Chris Henk <Chris.Henk@unobtainium.software>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/LittleBoxOfSunshine/json-mask"
readme = "README.md"
keywords = ["json", "mask", "filter", "schema"]

[dependencies]
serde_json = "1.0.96"
thiserror = "1.0.44"
jsonschema = "0.17.1"

[dev-dependencies]
uuid = { version = "1.4.1", features = ["serde"] }
