[package]
name = "json_mask"
version = "0.1.0"
edition = "2021"
authors = ["Chris Henk"]

[dependencies]
serde_json = "1.0.96"
serde = "1.0.160"
valico = "4.0.0"
thiserror = "1.0.44"

[dev-dependencies]
uuid = { version = "1.4.1", features = ["serde"] }
